// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLEXgnVO5FFcbd-esp0mspnWWjPlR9Bc',
    appId: '1:162654207861:web:b08def472aace1bd215d3c',
    messagingSenderId: '162654207861',
    projectId: 'sanad-99d2f',
    authDomain: 'sanad-99d2f.firebaseapp.com',
    storageBucket: 'sanad-99d2f.firebasestorage.app',
    measurementId: 'G-ZZPM8JXCEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZ2vuvCF2giH0ZxIREodNQcuCVotTZN8',
    appId: '1:162654207861:android:873688e3e386e04a215d3c',
    messagingSenderId: '162654207861',
    projectId: 'sanad-99d2f',
    storageBucket: 'sanad-99d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtS5ewl0CSn-ueSPt55MCGDDzGoJmq4js',
    appId: '1:162654207861:ios:f96b9bd7425e8381215d3c',
    messagingSenderId: '162654207861',
    projectId: 'sanad-99d2f',
    storageBucket: 'sanad-99d2f.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtS5ewl0CSn-ueSPt55MCGDDzGoJmq4js',
    appId: '1:162654207861:ios:f96b9bd7425e8381215d3c',
    messagingSenderId: '162654207861',
    projectId: 'sanad-99d2f',
    storageBucket: 'sanad-99d2f.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPLEXgnVO5FFcbd-esp0mspnWWjPlR9Bc',
    appId: '1:162654207861:web:0b6f1c1a93732e9a215d3c',
    messagingSenderId: '162654207861',
    projectId: 'sanad-99d2f',
    authDomain: 'sanad-99d2f.firebaseapp.com',
    storageBucket: 'sanad-99d2f.firebasestorage.app',
    measurementId: 'G-8JBS904RPF',
  );
}
